--银河
function c80700001.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetHintTiming(0,TIMINGS_CHECK_MONSTER)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
	e2:SetRange(LOCATION_SZONE)
	e2:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e2:SetTarget(c80700001.atktarget)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetRange(LOCATION_SZONE)
	e3:SetCode(EFFECT_SELF_DESTROY)
	e3:SetCondition(c80700001.descon)
	c:RegisterEffect(e3)
end
function c80700001.atktarget(e,c)
	return not c:IsRace(RACE_FAIRY)
end
function c80700001.descon(e)
	return not Duel.IsExistingMatchingCard(c80700001.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,nil,ft)
end
function c80700001.filter(c)
	return  c:IsRace(RACE_FAIRY)
end
